/**
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An order for a pets from the pet store
 *
 * @param id 
 * @param petId 
 * @param quantity 
 * @param shipDate 
 * @param status Order Status
 * @param complete 
 */
@Serializable@JsonClass(generateAdapter = true)
data class Order (

    @SerialName(value = "id") var id: kotlin.Long? = null,

    @SerialName(value = "petId") var petId: kotlin.Long? = null,

    @SerialName(value = "quantity") var quantity: kotlin.Int? = null,

    @SerialName(value = "shipDate") var shipDate: kotlin.String? = null,

    /* Order Status */
    @SerialName(value = "status") var status: Order.Status? = null,

    @SerialName(value = "complete") var complete: kotlin.Boolean? = false

) {

    /**
     * Order Status
     *
     * Values: placed,approved,delivered
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "placed") placed("placed"),
        @SerialName(value = "approved") approved("approved"),
        @SerialName(value = "delivered") delivered("delivered");
    }
}

