/**
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Category
import org.openapitools.client.models.Tag

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A pet for sale in the pet store
 *
 * @param name 
 * @param photoUrls 
 * @param id 
 * @param category 
 * @param tags 
 * @param status pet status in the store
 */
@Serializable@JsonClass(generateAdapter = true)
data class Pet (

    @SerialName(value = "name") @Required var name: kotlin.String,

    @SerialName(value = "photoUrls") @Required var photoUrls: kotlin.Array<kotlin.String>,

    @SerialName(value = "id") var id: kotlin.Long? = null,

    @SerialName(value = "category") var category: Category? = null,

    @SerialName(value = "tags") var tags: kotlin.Array<Tag>? = null,

    /* pet status in the store */
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "status") var status: Pet.Status? = null

) {

    /**
     * pet status in the store
     *
     * Values: available,pending,sold
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "available") available("available"),
        @SerialName(value = "pending") pending("pending"),
        @SerialName(value = "sold") sold("sold");
    }
}

